import { test, expect } from '@playwright/test';
import { startFixture, testPassword } from '../support.mjs';

let fixture: Awaited<ReturnType<typeof startFixture>>;
test.beforeAll(async () => { fixture = await startFixture(18774); });
test.afterAll(async () => { await fixture?.stop(); });

test('leave intake switches to EWP and registers the requested fields', async ({ page }) => {
  await page.goto(`${fixture.base}/`);
  await page.getByLabel('Email address').fill('admin@example.test');
  await page.getByLabel('Password', { exact: true }).fill(testPassword);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await page.getByRole('button', { name: 'Leave Records', exact: true }).click();
  await page.getByRole('button', { name: 'Register Leave or EWP' }).click();
  await expect(page.getByText('1. Leave Intake Mode')).toBeVisible();
  await page.getByRole('button', { name: /EWP Record/ }).click();
  await page.locator('#leave-input-barcode').fill('EWP-BROWSER-001');
  await page.locator('#leave-input-applicant').fill('Browser Employee');
  await page.locator('#leave-select-office').selectOption({ index: 1 });
  await page.locator('#ewp-input-amount').fill('1750.50');
  await expect(page.locator('#ewp-input-amount')).toHaveValue('1,750.50');
  await page.locator('#ewp-input-purpose').fill('Medical assistance');
  await page.getByRole('textbox', { name: 'Remarks' }).fill('Submitted complete requirements');
  await page.getByRole('button', { name: 'Register EWP Record', exact: true }).click();
  await expect(page.getByRole('tab', { name: /EWP Records/ })).toHaveAttribute('aria-selected','true');
  await expect(page.getByText('Leave Registry')).toHaveCount(0);
  await expect(page.getByText('EWP-BROWSER-001')).toBeVisible();
  await expect(page.getByText('Browser Employee')).toBeVisible();
  await expect(page.getByText('Medical assistance')).toBeVisible();
  await page.reload();
  await expect(page.getByRole('tab', { name: /EWP Records/ })).toHaveAttribute('aria-selected','true');
  await expect(page.getByText('EWP-BROWSER-001')).toBeVisible();
  await page.screenshot({ path: 'test-results/leave-ewp-registry.png', fullPage: true });
});

test('leave date spans skip weekends in the preview and saved dates', async ({ page }) => {
  await page.clock.setFixedTime(new Date('2026-10-02T12:00:00Z'));
  await page.goto(`${fixture.base}/`);
  await page.getByLabel('Email address').fill('admin@example.test');
  await page.getByLabel('Password', { exact: true }).fill(testPassword);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await page.getByRole('button', { name: 'Leave Records', exact: true }).click();
  await page.getByRole('button', { name: 'Register Leave or EWP', exact: true }).click();
  await page.getByPlaceholder('Enter employee or applicant name').fill('Weekend Span Applicant');
  await page.getByLabel('Office *').selectOption("CEO - City Engineer's Office");
  await page.getByLabel(/Barcode \/ Tracking No/).fill('BROWSER-LEAVE-WEEKEND');
  await page.locator('#select-leave-subtype').selectOption('WITHIN_PHILIPPINES');
  await page.getByRole('button', { name: 'Select Leave Date Range' }).click();
  await expect(page.getByRole('button', { name: '2026-10-31' })).toBeDisabled();
  await page.getByRole('button', { name: '2026-10-30' }).click();
  await page.getByRole('button', { name: 'Next month' }).click();
  await expect(page.getByRole('button', { name: '2026-11-01' })).toBeDisabled();
  await page.getByRole('button', { name: '2026-11-02' }).click();
  await expect(page.locator('#calculated-leave-days')).toHaveText('2 days');
  await page.locator('#btn-submit-filing').click();
  const row = page.getByText('BROWSER-LEAVE-WEEKEND', { exact: true }).locator('xpath=ancestor::tr');
  await expect(row).toContainText('2');
  await row.getByRole('button', { name: 'Multiple Dates Selected' }).click();
  const dates = page.getByRole('dialog', { name: 'Inclusive Dates' });
  await expect(dates).toContainText('2 dates');
  await expect(dates.getByText('October 2026')).toBeVisible();
  await expect(dates.locator('time[data-date="2026-10-30"]')).toHaveAttribute('data-range-state', 'endpoint');
  await expect(dates.locator('time[data-date="2026-10-31"]')).toHaveAttribute('data-range-state', 'skipped');
  await dates.getByRole('button', { name: 'Next leave month' }).click();
  await expect(dates.getByText('November 2026')).toBeVisible();
  await expect(dates.locator('time[data-date="2026-11-01"]')).toHaveAttribute('data-range-state', 'skipped');
  await expect(dates.locator('time[data-date="2026-11-02"]')).toHaveAttribute('data-range-state', 'endpoint');
});
