CREATE TABLE IF NOT EXISTS app_state (
 state_key VARCHAR(64) PRIMARY KEY, state_json LONGTEXT NOT NULL,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, CHECK (JSON_VALID(state_json))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS app_users (
 id VARCHAR(64) PRIMARY KEY, email VARCHAR(190) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL, name VARCHAR(160) NOT NULL, role VARCHAR(64) NOT NULL,
 role_title VARCHAR(160) NOT NULL, office VARCHAR(190) NOT NULL, division VARCHAR(190) NOT NULL,
 position VARCHAR(190) NOT NULL, avatar_initials VARCHAR(8) NOT NULL, avatar_seed VARCHAR(190) NULL, sidebar_modules LONGTEXT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS app_meta (
 id INT PRIMARY KEY, revision BIGINT UNSIGNED NOT NULL DEFAULT 0, schema_version INT NOT NULL DEFAULT 0
) ENGINE=InnoDB;
INSERT IGNORE INTO app_meta (id) VALUES (1);
CREATE TABLE IF NOT EXISTS app_records (
 collection VARCHAR(64) NOT NULL, id VARCHAR(190) NOT NULL, record_json LONGTEXT NOT NULL,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (collection,id), CHECK (JSON_VALID(record_json))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS app_audit (
 sequence BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, id VARCHAR(64) NOT NULL UNIQUE,
 record_json LONGTEXT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, CHECK (JSON_VALID(record_json))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS app_files (
 id VARCHAR(64) PRIMARY KEY, original_name VARCHAR(255) NOT NULL, mime_type VARCHAR(120) NOT NULL,
 size_bytes BIGINT UNSIGNED NOT NULL, sha256 CHAR(64) NOT NULL, uploaded_by VARCHAR(64) NOT NULL,
 owner_id VARCHAR(64) NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX (owner_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS app_login_attempts (
 attempt_key CHAR(64) PRIMARY KEY, attempts INT NOT NULL DEFAULT 0, window_start BIGINT NOT NULL
) ENGINE=InnoDB;
